kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user-access
  namespace: ma-v2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user-full-access
subjects:
- kind: Group
  namespace: ma-v2
  name: groupObjectId
